version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=YZwYfkoLfd5tPNcGtLuSbI8qnKStIM1U
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - VIRTUAL_HOST=localhost
      - CHECK_ORIGIN=true
      - TESLA_AUTH_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjI5Skh4dlVBVVFfbDlBVXFhcHBrV2dLRDhRRSJ9.eyJpc3MiOiJodHRwczovL2F1dGgudGVzbGEuY29tL29hdXRoMi92MyIsImF1ZCI6Imh0dHBzOi8vYXV0aC50ZXNsYS5jb20vb2F1dGgyL3YzL3Rva2VuIiwiaWF0IjoxNzQ0ODc1OTc2LCJzY3AiOlsib3BlbmlkIiwib2ZmbGluZV9hY2Nlc3MiXSwib3VfY29kZSI6Ik5BIiwiZGF0YSI6eyJ2IjoiMSIsImF1ZCI6Imh0dHBzOi8vb3duZXItYXBpLnRlc2xhbW90b3JzLmNvbS8iLCJzdWIiOiJhZDE0ZjUzNC0yMTA1LTRjYjYtOWZiZC0wYjNmMDM4YTMxOGUiLCJzY3AiOlsib3BlbmlkIiwiZW1haWwiLCJvZmZsaW5lX2FjY2VzcyJdLCJhenAiOiJvd25lcmFwaSIsImFtciI6WyJwd2QiLCJtZmEiLCJvdHAiXSwiYXV0aF90aW1lIjoxNzQ0ODc1OTc2fX0.NLeR_1l_cebDlR369XK2N9WL_T_YKdJoy9BvJ-SCQg0n_Yhq9mhZFIIdGc8OUdHxLuYC1vZFhqle-nteEyZEImddAuRwxsbTT35btn5VTtKe19ZVYThsXqrAT6IEykAQt4GVz9yF33Zz2HCh9fjBdxsnih_cb9IxXsEPFgxVZOBg25b8LiGj9OTt1XkQDy5WBquGsYKp_0P9jYSLkFpM632ARPQk9jS9jye_xnGfxuj0N_LVGqw5RkcDqvg-4RqZBszQRIM6myC6TdrunZzIW1peoItaUGO_ZYNiHNMmJNii_tA8DgYMwlAF6BfRJ3z4KPmSyzgF6A7HSywhY25FTQ
      - ENCRYPTION_KEY=XYiu1nN/Or9d64/qhACPU0zL5BtNZnDIy/5hr80PwZpG5NJy+V3PIDwQG
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    depends_on:
      - database
      - mosquitto

  database:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=YZwYfkoLfd5tPNcGtLuSbI8qnKStIM1U
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=YZwYfkoLfd5tPNcGtLuSbI8qnKStIM1U
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - VIRTUAL_HOST=localhost
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
