
apiVersion: 1
datasources:
  - name: TeslaMate
    type: postgres
    access: proxy
    url: database:5432
    database: teslamate
    user: teslamate
    secureJsonData:
      password: "YZwYfkoLfd5tPNcGtLuSbI8qnKStIM1U"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: false

